Remove File.separator in Paths.get()
wso2/carbon-maven-plugins pull request #70
Opened 2017-06-29 13:37 UTC by kasunsiyambalapitiya

Resolve #69

2017-08-02 16:38 UTC, Niranjan-K requested changes

2017-08-02 16:38 UTC, Niranjan-K commented on carbon-feature-plugin/src/main/java/org/wso2/maven/p2/feature/install/FeatureInstaller.java
> +        File eclipseIni = Paths.get(profileLocation , "eclipse.ini").toFile();
need to code format. extra space after "profileLocation"

2017-08-02 16:38 UTC, Niranjan-K commented on carbon-feature-plugin/src/main/java/org/wso2/maven/p2/utils/FileManagementUtil.java
> +        return Paths.get(destination , profile , "configuration" , "config.ini").toFile();
same as above

2017-08-02 18:24 UTC, kasunsiyambalapitiya commented on carbon-feature-plugin/src/main/java/org/wso2/maven/p2/feature/install/FeatureInstaller.java
> +        File eclipseIni = Paths.get(profileLocation , "eclipse.ini").toFile();
fixed in 1b68b28 commit

2017-08-02 18:24 UTC, kasunsiyambalapitiya commented on carbon-feature-plugin/src/main/java/org/wso2/maven/p2/utils/FileManagementUtil.java
> +        return Paths.get(destination , profile , "configuration" , "config.ini").toFile();
fixed in 1b68b28 commit

2017-08-03 08:11 UTC, Niranjan-K approved these changes

2017-08-03 08:11 UTC, merged